### PR TITLE
Issue #222: Hide status fields and delete btn. Add Cancel btn.

### LINKED ISSUE #222: Theme individial build section edit pages
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5476612407

---

This task refers to the page the user sees when they click 'edit' on the build page.

Much of this has been done on RSAMS, refer to that as a reference and any needed code.

### Remove extraneous elements

1. Remove the _About formats_ link that appears under each textarea field
2. Remove the _Publish_ checkbox
3. Remove the Drupal vertical tab menu  
   image

### Items to add
1.  Delete should be a Cancel button, clicking this takes user back to the build page without any changes being applied.

### functionality adjustments

- if a dropdown has 3 or less options, use buttons instead  
in this example, _Remove_ and _duplicate_ would be exposed as buttons
image

## Theme adjustments

Apply the layout, colours and icons as per the prototype.

> **NOTE:** BC uses a customized bootstrap approach to icons. [read the wiki page on icons in the BC base-build](https://github.com/bcgov/bcbb/wiki/Using-icons)

- [mobile](https://www.figma.com/proto/QFQoyhpG1qvtBwVuuBVikk/design-prototypes?type=design&node-id=390-26771&t=1vOqU2Mw0YjNWtFo-1&scaling=scale-down&page-id=291%3A12856&starting-point-node-id=373%3A19167&mode=design)
- [desktop](https://www.figma.com/proto/QFQoyhpG1qvtBwVuuBVikk/design-prototypes?type=design&node-id=567-8238&t=cjQMwHvpF3rL826Z-1&scaling=scale-down&page-id=381%3A19173&starting-point-node-id=381%3A19302&mode=design)

## DoD

- [ ] About formats is removed
- [ ] publish checkbox is removed
- [ ] Drupal vertical tabs are removed
- [ ] Cancel button has been added
- [ ] Clicking _Cancel_ takes people back to the build pages without applying changes
- [ ] Layout looks like the prototype
- [ ] Icons added to buttons
- [ ] buttons are used instead of drupdowns if there are 3 or less options

### PR DESCRIPTION
**Pull request by gurjinder12**

### CODE REVIEW

**Comment by joel-osc** [comment]
Not a fan of this implementation... browser back button is not reliable. Why not do it the same way as in RSAMS?

**Comment by gurjinder12** [comment]
> Not a fan of this implementation... browser back button is not reliable. Why not do it the same way as in RSAMS?

I can set custom submit handle on cancel btn and handle will have formstate->setRedirect, but that will not work if one of the field is empty and required.

**Comment by joel-osc** [comment]
Why not just add the cancel_button module like on rsams???

**Comment by gurjinder12** [comment]
> Why not just add the cancel_button module like on rsams???

OK adding  cancel_button module, I update the code and it kind of doing same.

**Review by lkmorlan — APPROVED** [review]

**Pull request merged**
