### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by NicoledeGreef**
GNU GPL 2 as applicable to Drupal

### CODE REVIEW

**Review by lkmorlan — APPROVED** [review]

**Comment by lkmorlan** [comment]
@NicoledeGreef This pull request added a copy of the GPL but it did not add a copyright statement, which the GPL directs to be done. I have added a few more commits which add a copyright statement and make related changes. Please let me know if you agree with these changes.

**Review by NicoledeGreef — COMMENTED** [review]
This addition looks good to me - thank you for catching that.

**Review by NicoledeGreef — COMMENTED** [review]
The copyright addition looks good to me - thank you for catching that.

**Review by NicoledeGreef — COMMENTED** [review]
I'm not certain if the repomountie bot will recognize this filename as a license.  It may be expecting LICENSE;
please see: https://github.com/bcgov/repomountie#license

**Comment by lkmorlan** [comment]
I have renamed the file.

**Pull request merged**
